name: Publish to npm

on:
  push:
    tags:
      - 'v*' # Publicará solo cuando se cree un tag que comience con "v"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build the library
        run: npm run build-library

      - name: Publish to npm
        working-directory: dist/ngx-calendario
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
